#!/usr/bin/env python3
"""migx-fleet-conductor — prioritize open federation mail and emit next actions.

Owns the "who wakes next" loop for Claude / Codex / Grok (Antigravity paused) without a human ferrying chat.
Does not start CLIs by default (no auto-spawn of heavy agents). Use --nudge-file for a machine-
readable queue peers can poll; --drain-codex runs built-in seal-class drains (e.g. EXO P-08).

See: kanban/knowledge/fleet-operating-model.md · kanban/runbooks/fleet-conductor.md
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import re
import subprocess
import sys
from pathlib import Path

# Severity rank (higher first)
SEV = {"blocker": 100, "high": 80, "medium": 50, "low": 20}
# Prefer seal-class / eval work slightly
SUBJECT_BOOST = (
    (re.compile(r"p-?08|evaluat|verify|seal|evd|bench", re.I), 25),
    (re.compile(r"wave1|execute|implement", re.I), 15),
    (re.compile(r"research|signal|scout", re.I), 10),
    (re.compile(r"bootstrap|online", re.I), -30),
)

# Default peer priority when severities equal: unblock product chain.
PEER_TIEBREAK = {
    "codex-cli": 40,  # evaluator first when mail pending
    "claude-code": 30,
    "grok-signal": 10,
    "gudjon": 0,
}

ACTIVE_SIDES = frozenset({"grok-signal", "claude-code", "codex-cli", "gudjon"})
PAUSED_PEERS = frozenset({"antigravity-cli"})


def repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def fed_root(root: Path) -> Path:
    return root / "kanban" / "federation"


def parse_frontmatter(text: str) -> dict[str, str]:
    if not text.startswith("---"):
        return {}
    end = text.find("\n---", 3)
    if end < 0:
        return {}
    out: dict[str, str] = {}
    for line in text[3:end].splitlines():
        if ":" not in line:
            continue
        k, v = line.split(":", 1)
        out[k.strip()] = v.strip().strip("\"'")
    return out


def load_active(root: Path) -> list[dict]:
    """open + ack messages (ack = in progress, still needs attention)."""
    rows: list[dict] = []
    for status in ("open", "ack"):
        d = fed_root(root) / "messages" / status
        if not d.is_dir():
            continue
        for p in sorted(d.glob("*.md")):
            if p.name.startswith("_"):
                continue
            text = p.read_text(encoding="utf-8", errors="replace")
            fm = parse_frontmatter(text)
            if fm.get("to", "") not in ACTIVE_SIDES:
                continue
            rows.append(
                {
                    "path": p,
                    "status": status,
                    "fm": fm,
                    "id": fm.get("id", p.stem),
                    "to": fm.get("to", ""),
                    "from": fm.get("from", ""),
                    "type": fm.get("type", ""),
                    "severity": fm.get("severity", "medium"),
                    "subject": fm.get("subject", ""),
                    "acceptance": fm.get("acceptance", ""),
                }
            )
    return rows


def score(row: dict) -> float:
    # Paused peers (e.g. antigravity-cli — no tokens) never win NEXT.
    if row.get("to") in PAUSED_PEERS or row.get("to") not in ACTIVE_SIDES:
        return -1e9
    s = float(SEV.get(row["severity"], 40))
    if row["status"] == "ack":
        s += 5  # finish in-flight first
    for rx, boost in SUBJECT_BOOST:
        if rx.search(row["subject"]) or rx.search(row["id"]):
            s += boost
    s += PEER_TIEBREAK.get(row["to"], 0) / 100.0
    return s


def nudge_line(row: dict) -> str:
    side = row["to"]
    mid = row["id"]
    return (
        f"export MIGX_FED_SIDE={side} MIGX_REPO_ROOT=\"$(git rev-parse --show-toplevel)\"\n"
        f"./kanban/scripts/migx-fed poll --to {side}\n"
        f"# then: ack if open → act → close --id {mid} --by {side}\n"
        f"./kanban/scripts/migx-fed ack --id {mid} --by {side}   # if still open\n"
    )


def write_nudge(root: Path, ranked: list[dict]) -> Path:
    out_dir = fed_root(root) / "scratchpad" / "conductor"
    out_dir.mkdir(parents=True, exist_ok=True)
    stamp = dt.datetime.now(dt.timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    path = out_dir / f"nudge-{stamp}.md"
    lines = [
        f"# Fleet conductor nudge — {stamp}",
        "",
        "Generated by `kanban/scripts/migx-fleet-conductor.py`. Not committed (scratchpad).",
        "",
    ]
    if not ranked:
        lines.append("**Inbox empty.** No peer wake required.")
    else:
        top = ranked[0]
        lines.append(f"## NEXT DRI: `{top['to']}` (score={score(top):.1f})")
        lines.append(f"- mail: `{top['id']}`")
        lines.append(f"- status: {top['status']} · severity: {top['severity']}")
        lines.append(f"- subject: {top['subject']}")
        lines.append(f"- acceptance: {top['acceptance']}")
        lines.append("")
        lines.append("### Commands")
        lines.append("```bash")
        lines.append(nudge_line(top).rstrip())
        lines.append("```")
        lines.append("")
        lines.append("## Full queue (priority order)")
        for i, r in enumerate(ranked, 1):
            lines.append(
                f"{i}. **{r['to']}** ← {r['id']} [{r['status']}/{r['severity']}] {r['subject']}"
            )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    # stable pointer
    latest = out_dir / "LATEST.md"
    latest.write_text(path.read_text(encoding="utf-8"), encoding="utf-8")
    return path


def run_drain_codex(root: Path, json_mode: bool = False) -> int:
    """Run seal-class drains that codex-cli owns when mail is open/ack."""
    script = root / "kanban" / "scripts" / "migx-codex-drain.py"
    if not script.is_file():
        print("missing migx-codex-drain.py", file=sys.stderr)
        return 2
    out = sys.stderr if json_mode else None
    return subprocess.call([sys.executable, str(script), "--root", str(root)], stdout=out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--root", type=Path, default=None)
    ap.add_argument("--json", action="store_true", help="machine-readable ranked queue")
    ap.add_argument("--nudge-file", action="store_true", help="write scratchpad/conductor/LATEST.md")
    ap.add_argument(
        "--drain-codex",
        action="store_true",
        help="run codex seal-class drains (EXO P-08, etc.) if mail pending",
    )
    ap.add_argument(
        "--once",
        action="store_true",
        help="single pass (default); future: --watch",
    )
    args = ap.parse_args()
    root = (args.root or repo_root()).resolve()

    ranked = sorted(load_active(root), key=score, reverse=True)

    if args.drain_codex:
        rc = run_drain_codex(root, json_mode=args.json)
        # reload after drain
        ranked = sorted(load_active(root), key=score, reverse=True)
        if rc != 0:
            print(f"drain-codex exit {rc}", file=sys.stderr)

    if args.json:
        payload = [
            {
                "id": r["id"],
                "to": r["to"],
                "from": r["from"],
                "status": r["status"],
                "severity": r["severity"],
                "subject": r["subject"],
                "score": score(r),
                "path": str(r["path"].relative_to(root)),
            }
            for r in ranked
        ]
        print(json.dumps({"generated_utc": dt.datetime.now(dt.timezone.utc).isoformat(), "queue": payload}, indent=2))
    else:
        stamp = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        print(f"# Fleet conductor @ {stamp}")
        print(f"root: {root}")
        print(f"active mail (open+ack): {len(ranked)}\n")
        if not ranked:
            print("Inbox empty — no wake.")
        else:
            for i, r in enumerate(ranked, 1):
                print(
                    f"{i}. [{score(r):5.1f}] {r['to']:<18} {r['status']}/{r['severity']:<7} "
                    f"{r['id']}"
                )
                print(f"      subject: {r['subject']}")
            top = ranked[0]
            print(f"\n## NEXT\n**DRI = `{top['to']}`** for `{top['id']}`\n")
            print("```bash")
            print(nudge_line(top).rstrip())
            print("```")

    if args.nudge_file:
        p = write_nudge(root, ranked)
        out = sys.stderr if args.json else sys.stdout
        print(f"\nnudge written: {p.relative_to(root)}", file=out)
        print(f"pointer:       kanban/federation/scratchpad/conductor/LATEST.md", file=out)

    return 0


if __name__ == "__main__":
    sys.exit(main())
